### ISSUE TITLE
Not compatible with v2019.3

### ISSUE THREAD

**Issue by ktalebian** [EmmyLua/IntelliJ-EmmyLua#312]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | Ultimate 2019.3
 EmmyLua version | 1.3.0.99-IDEA182
 OS                        | OSX 10.14.6

This plugin is not compatible with the latest version of intelliJ

**Comment by pytpeng** [comment]
same issue，wait for updating

**Comment by nitramwin** [comment]
Same issue. The reason is that the EmmyLua version available in the Plugin Marketplace has not yet been updated. 

1. To do so, download 1.3.0.135 from here: https://ci.appveyor.com/project/EmmyLua/intellij-emmylua/build/artifacts and keep the folder zipped.
2. In CLion, go to FILE>SETTINGS>PLUGINS and then click on installed.
3. Rightclick on existing EmmyLua plugin and uninstall. Restart CLion.
4. Again go to file>settings>plugins and then  click on the wheel next to Marketplace and Installed. Select the option 'install Plugin from disk' and restart the IDE again.

It should work now.

**Comment by Apollon77** [comment]
> The reason is that the EmmyLua version available in the Plugin Marketplace has not yet been updated.

When this can be expected? because manual install will then lead to getting no further updates automatically, or?!

**Comment by tangzx** [comment]
v1.3.1 is pending JetBrains approval
https://plugins.jetbrains.com/plugin/9768-emmylua

**Comment by jorn86** [comment]
Any idea what's taking them so long? Looks like it's been pending approval for four months already.

**Comment by tangzx** [comment]
![image](https://user-images.githubusercontent.com/3354360/71307085-eacd4d80-2423-11ea-8149-1f6daee2500c.png)

> The request will be processed within two business days.

**Comment by jorn86** [comment]
ah I see, I was looking at the previous one from august, probably because I can't see the new one yet. Thanks!

**Comment by tangzx** [comment]
v1.3.1 had been approved by JetBrains!
