### ISSUE TITLE
False syntax error

### ISSUE THREAD

**Issue by p-josue** [EmmyLua/IntelliJ-EmmyLua#345]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | PS-193.6494.47
 EmmyLua version | 1.3.2.142-IDEA182
 OS                        |  Windows 10

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
Just write this code
IsControlPressed(0, isRDR and `INPUT_MP_TEXT_CHAT_ALL` or 245)

What happens?（出现什么问题？）
-------------
Highlight work wrong, system warn a syntax error

What were you expecting to happen?（期望？）
-----------------------------------------
I think is a correct code, this code isn't mine but doesn't go in error when I run it

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
No errors

Any other comments?（其它说明）
------------------------
This is an screenshoot
https://imgur.com/pTo4jDl

**Comment by adriweb** [comment]
There is no mistake, "`" is not a valid symbol in Lua (except in a string), so it is a syntax error.

**Comment by p-josue** [comment]
Thanks for the answer, in my test it works, I don't know if this is the beta version of lua or something different. I will ask you, if you have time, to try this steps please:
1 Go to fivem and follow the steps to create a server (is lua based and really easy&fast to setup) https://docs.fivem.net/docs/server-manual/setting-up-a-server/
2 In the step 4 you has to download server-data with some resources, the resource that has this character is in this path `server-data /resources/[gameplay]/chat/cl.lua:199`
3 This works without any problem if you start the server and you can try in server side to easy debug without buying the game

**Comment by adriweb** [comment]
They use a custom Lua interpreter that adds this as a feature specific to their purposes, as indicated here: https://cookbook.fivem.net/2019/06/23/lua-support-for-compile-time-jenkins-hashes/

**Comment by p-josue** [comment]
Really really sorry for making you losing time, thanks for the answer.

**Comment by hojgr** [comment]
Hello! There is large community of FiveM (GTA 5 multiplayer platform) that would love to use Intellij IDEA with your plugin but we can't because it does not support the backtick.

Backtick, in FiveM lua is a special type of string that is translated into a hash during compilation.

I'd love to fork your project and add this feature just for the fivem community, but I cant quite find the lexer/ast parser in the repo.

I've already added the support to Lua lexer that I'm using for transforming Lua to AST and I think I can do so in here, but would love some pointers just to make it a bit easier for me :) 

thanks

**Comment by rizzdev** [comment]
Can anything be done about this? It is effecting a lot of FiveM developers.
